const products = [
  // BMW
  {
    id: 1,
    title: "BMW Запалителни свещи",
    brand: "bmw",
    price: 19.99,
    rating: 4,
    image: "img/bmwParts/bmw-sweshti.jpg",
    description: "Комплект запалителни свещи, подходящ за BMW модели.",
  },
  {
    id: 2,
    title: "BMW Спирачни накладки",
    brand: "bmw",
    price: 26.93,
    rating: 5,
    image: "img/bmwParts/bmw-nakladki.jpg",
    description: "Комплект спирачни накладки за BMW автомобили.",
  },
  {
    id: 3,
    title: "BMW Спирачни дискове",
    brand: "bmw",
    price: 42.93,
    rating: 4,
    image: "img/bmwParts/bmw-diskowe.jpg",
    description: "Комплект спирачни дискове за BMW автомобили.",
  },
  {
    id: 4,
    title: "BMW Амортисьори",
    brand: "bmw",
    price: 261.83,
    rating: 5,
    image: "img/bmwParts/bmw-amortisiori.jpg",
    description: "Комплект амортисьори за BMW автомобили.",
  },

  // Mercedes
  {
    id: 5,
    title: "Mercedes Запалителни свещи",
    brand: "mercedes",
    price: 21,
    rating: 5,
    image: "img/mercedesParts/mercedes-sweshti.jpg",
    description: "Комплект запалителни свещи за стабилна работа на двигателя.",
  },
  {
    id: 6,
    title: "Mercedes Спирачни накладки",
    brand: "mercedes",
    price: 94.99,
    rating: 5,
    image: "img/mercedesParts/mercedes-nakladki.jpg",
    description: "Комплект спирачни накладки за Mercedes автомобили.",
  },
  {
    id: 7,
    title: "Mercedes Спирачни дискове",
    brand: "mercedes",
    price: 49.57,
    rating: 3,
    image: "img/mercedesParts/mercedes-diskowe.jpg",
    description: "Комплект спирачни дискове за Mercedes автомобили.",
  },
  {
    id: 8,
    title: "Mercedes амортисьори ",
    brand: "mercedes",
    price: 19.99,
    rating: 4,
    image: "img/mercedesParts/mercedes-amortisiori.jpg",
    description:
      "Комплект амортисьори за Mercedes автомобили за добра стабилност на пътя.",
  },

  // Audi
  {
    id: 9,
    title: "Audi Запалителни свещи",
    brand: "audi",
    price: 30.99,
    rating: 4,
    image: "img/audiParts/audi-sweshti.jpg",
    description: "Комплект запалителни свещи за стабилна работа на двигателя.",
  },
  {
    id: 10,
    title: "Audi Спирачни накладки",
    brand: "audi",
    price: 40.9,
    rating: 4,
    image: "img/audiParts/audi-nakladki.jpg",
    description: "Комплект спирачни накладки за Audi.",
  },
  {
    id: 11,
    title: "Audi Спирачни дискове",
    brand: "audi",
    price: 52.7,
    rating: 5,
    image: "img/audiParts/audi-diskowe.jpg",
    description: "Комплект спирачни дискове за стабилно и сигурно спиране.",
  },
  {
    id: 12,
    title: "Audi Амортисьори",
    brand: "audi",
    price: 328.8,
    rating: 5,
    image: "img/audiParts/audi-amortisiori.jpg",
    description: "Комплект спортни амортисьори за Audi автомобили",
  },

  // Subaru
  {
    id: 13,
    title: "Subaru Запалителни свещи",
    brand: "subaru",
    price: 23.99,
    rating: 5,
    image: "img/subaruParts/subaru-sweshti.jpg",
    description: "Комплект запалителни свещи, подходящи за Subaru модели.",
  },
  {
    id: 14,
    title: "Subaru Спирачни накладки",
    brand: "subaru",
    price: 30.5,
    rating: 4,
    image: "img/subaruParts/subaru-nakladki.jpg",
    description: "Комплект спирачни накладки за Subaru.",
  },
  {
    id: 15,
    title: "Subaru Спирачни дискове",
    brand: "subaru",
    price: 129.99,
    rating: 3,
    image: "img/subaruParts/subaru-diskowe.jpg",
    description:
      "Комплект спирачни дискове за надеждно спиране и контрол Subaru.",
  },
  {
    id: 16,
    title: "Subaru Амортисьори",
    brand: "subaru",
    price: 250,
    rating: 4,
    image: "img/subaruParts/subaru-amortisiori.jpg",
    description: "Комплект спортно окачване за Subaru.",
  },

  //Toyota
  {
    id: 17,
    title: "Toyota Запалителни свещи",
    brand: "toyota",
    price: 21.99,
    rating: 4,
    image: "img/toyotaParts/toyota-sweshti.jpg",
    description: "Комплект запалителни свещи за Toyota автомобили.",
  },
  {
    id: 18,
    title: "Toyota Спирачни накладки",
    brand: "toyota",
    price: 32.7,
    rating: 5,
    image: "img/toyotaParts/toyota-nakladki.jpg",
    description: "Комплект Toyota накладки за моментално спиране.",
  },
  {
    id: 19,
    title: "Toyota Спирачни дискове",
    brand: "toyota",
    price: 27.5,
    rating: 5,
    image: "img/toyotaParts/toyota-diskowe.jpg",
    description: "Комплект спирачни дискове за Toyota модели.",
  },
  {
    id: 20,
    title: "Toyota Амортисьори",
    brand: "toyota",
    price: 200,
    rating: 5,
    image: "img/toyotaParts/toyota-amortisiori.jpg",
    description: "Комплект надеждени амортисьори за Toyota автомобили.",
  },
];
